#!/usr/bin/env node

const GOLDEN_WORKBENCH_INSTALLED_PROOF_MANIFEST = [
  {
    manifestRowId: 'home',
    id: 'new-chat-landing',
    route: '/home',
    screenshot: '00-new-chat-landing.png',
    artifactName: 'screenshots/00-new-chat-landing.png',
    closeoutState: 'waived',
    settledMarkers: ['New Chat', 'evaOS Workbench'],
  },
  {
    manifestRowId: 'business-browser',
    id: 'business-browser',
    route: '/business-browser',
    screenshot: '11-business-browser.png',
    artifactName: 'screenshots/11-business-browser.png',
    closeoutState: 'loaded',
    settledMarkers: ['Shared Browser'],
  },
  {
    manifestRowId: 'connected-apps',
    id: 'connected-apps',
    route: '/connected-apps',
    screenshot: '14-connected-apps.png',
    artifactName: 'screenshots/14-connected-apps.png',
    closeoutState: 'loaded',
    settledMarkers: ['Connected Apps', 'Customer context'],
  },
  {
    manifestRowId: 'people-access',
    id: 'people-access',
    route: '/people-access',
    screenshot: '15-people-and-access.png',
    artifactName: 'screenshots/15-people-and-access.png',
    closeoutState: 'loaded',
    settledMarkers: ['People & Access', 'Customer context'],
  },
  {
    manifestRowId: 'company-brain',
    id: 'company-brain',
    route: '/company-brain',
    screenshot: '16-company-brain.png',
    artifactName: 'screenshots/16-company-brain.png',
    closeoutState: 'loaded',
    settledMarkers: ['Company Brain', 'Website handoff', 'Open dashboard'],
  },
  {
    manifestRowId: 'evaos-dashboard',
    id: 'evaos',
    route: '/evaos',
    screenshot: '07-evaos.png',
    artifactName: 'screenshots/07-evaos.png',
    closeoutState: 'denied',
    settledMarkers: ['evaOS'],
  },
  {
    manifestRowId: 'hermes-dashboard',
    id: 'hermes',
    route: '/hermes',
    screenshot: '08-hermes.png',
    artifactName: 'screenshots/08-hermes.png',
    closeoutState: 'denied',
    settledMarkers: ['Hermes'],
  },
  {
    manifestRowId: 'mission-control',
    id: 'mission-control',
    route: '/mission-control',
    screenshot: '09-mission-control.png',
    artifactName: 'screenshots/09-mission-control.png',
    closeoutState: 'loaded',
    settledMarkers: ['Mission Control'],
  },
  {
    manifestRowId: 'terminal',
    id: 'terminal',
    route: '/terminal',
    screenshot: '10-terminal.png',
    artifactName: 'screenshots/10-terminal.png',
    closeoutState: 'denied',
    settledMarkers: ['Terminal'],
  },
  {
    manifestRowId: 'native-companion',
    id: 'mac-iphone',
    route: '/native-companion',
    screenshot: '06-mac-iphone.png',
    artifactName: 'screenshots/06-mac-iphone.png',
    closeoutState: 'loaded',
    settledMarkers: ['Mac & iPhone', 'Boundary clean'],
  },
  {
    manifestRowId: 'footer',
    id: 'sidebar-footer',
    route: '/guid',
    screenshot: '01-sidebar-footer.png',
    artifactName: 'screenshots/01-sidebar-footer.png',
    closeoutState: 'loaded',
    settledMarkers: ['evaOS Workbench', 'New Chat', 'Settings'],
  },
  {
    manifestRowId: 'branding',
    id: 'settings-about',
    route: '/settings/about',
    hashRoute: '/settings/model',
    screenshot: '05-settings-about.png',
    artifactName: 'screenshots/05-settings-about.png',
    action: 'click-settings-about',
    closeoutState: 'loaded',
    settledMarkers: ['evaOS Workbench', 'Build identity', 'Mac release', 'com.evaos.workbench', 'evaos-workbench'],
  },
];

module.exports = {
  GOLDEN_WORKBENCH_INSTALLED_PROOF_MANIFEST,
};
